name: Terraform Backend Deploy

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose action'
        required: true
        type: choice
        options:
          - plan
          - apply
        default: plan

permissions:
  contents: read
  id-token: write

jobs:
  checks:
    uses: ./.github/workflows/terraform-checks.yml
    with:
      working-directory: terraform-backend

  deploy-main:
    needs: checks
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_ARN }}
          aws-region:     ${{ secrets.AWS_REGION }}
          role-session-name: github-actions-terraform-main

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.4.0"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        if: ${{ github.event.inputs.action == 'plan' || github.event.inputs.action == 'apply' }}
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        run: terraform apply -auto-approve tfplan
